enum {
  TOKEN_YYerror = 0x100,
  TOKEN_YYUNDEF = 0x101,
  TOKEN_ERROR = 0x102,
  TOKEN_IDENTIFIER,
  TOKEN_FILENAME,
  TOKEN_CLASS,
  TOKEN_VAR,
  TOKEN_FUNCTION,
  TOKEN_NAMESPACE,
  TOKEN_USING,
  TOKEN_CONSTRUCTOR,
  TOKEN_DESTRUCTOR,
  TOKEN_COLON,
  TOKEN_LEFT_CURLY,
  TOKEN_RIGHT_CURLY
};
