extern "C" {
const char * yytname [162] = {
  "$end", "error", "$undefined", "TOKEN_ERROR", "TOKEN_BOOL_OR", "TOKEN_BOOL_AND", "TOKEN_BIT_OR", "TOKEN_BIT_XOR", "TOKEN_BIT_AND", "TOKEN_EQUALITY",
  "TOKEN_SUPER_EQUALITY", "TOKEN_INEQUALITY", "TOKEN_SUPER_INEQUALITY", "TOKEN_EQUALS", "TOKEN_LESS", "TOKEN_GREATER", "TOKEN_LESS_EQUAL", "TOKEN_GREATER_EQUAL", "TOKEN_SHIFT_LEFT", "TOKEN_SHIFT_RIGHT",
  "TOKEN_PLUS", "TOKEN_MINUS", "TOKEN_MULTIPLY", "TOKEN_DIVIDE", "TOKEN_MOD", "TOKEN_NOT", "TOKEN_TILDA", "TOKEN_DOLLAR", "TOKEN_PERIOD", "TOKEN_COMMA",
  "TOKEN_COLON", "TOKEN_SEMICOLON", "TOKEN_FUNCTION", "TOKEN_CONDITIONAL", "TOKEN_RETURN", "TOKEN_CLASS", "TOKEN_VAR", "TOKEN_CONSTRUCTOR", "TOKEN_DESTRUCTOR", "TOKEN_ARROW",
  "TOKEN_THREAD", "TOKEN_UNDEFINED", "TOKEN_SELF", "TOKEN_WORLD", "TOKEN_CLASSES", "TOKEN_LEVEL", "TOKEN_GAME", "TOKEN_ANIM", "TOKEN_IF", "TOKEN_ELSE",
  "TOKEN_DO", "TOKEN_WHILE", "TOKEN_FOR", "TOKEN_FOREACH", "TOKEN_IN", "TOKEN_INC", "TOKEN_DEC", "TOKEN_BIT_OR_EQUALS", "TOKEN_BIT_XOR_EQUALS", "TOKEN_BIT_AND_EQUALS",
  "TOKEN_SHIFT_LEFT_EQUALS", "TOKEN_SHIFT_RIGHT_EQUALS", "TOKEN_PLUS_EQUALS", "TOKEN_MINUS_EQUALS", "TOKEN_MULTIPLY_EQUALS", "TOKEN_DIVIDE_EQUALS", "TOKEN_MOD_EQUALS", "TOKEN_SIZE_FIELD", "TOKEN_USING_ANIMTREE", "TOKEN_CUR_ANIMTREE",
  "TOKEN_NAMESPACE", "TOKEN_USING", "TOKEN_PRECACHE", "TOKEN_DOUBLE_COLON", "TOKEN_WAITTILL", "TOKEN_WAITTILLMATCH", "TOKEN_WAITTILLFRAMEEND", "TOKEN_WAIT", "TOKEN_NOTIFY", "TOKEN_ENDON",
  "TOKEN_SWITCH", "TOKEN_CASE", "TOKEN_DEFAULT", "TOKEN_BREAK", "TOKEN_CONTINUE", "TOKEN_FALSE", "TOKEN_TRUE", "TOKEN_ASSERT", "TOKEN_ASSERTMSG", "TOKEN_ISDEFINED",
  "TOKEN_AUTOEXEC", "TOKEN_CONSTANT", "TOKEN_CODECALL", "TOKEN_PRIVATE", "TOKEN_ELLIPSIS", "TOKEN_DEVBLOCK_BEGIN", "TOKEN_DEVBLOCK_END", "TOKEN_LEFT_CURLY", "TOKEN_RIGHT_CURLY", "TOKEN_LEFT_PAREN",
  "TOKEN_RIGHT_PAREN", "TOKEN_LEFT_BRACKET", "TOKEN_RIGHT_BRACKET", "TOKEN_NEW", "TOKEN_HSTRING", "TOKEN_INTEGER", "TOKEN_FLOAT", "TOKEN_IDENTIFIER", "TOKEN_STRING", "TOKEN_ISTRING",
  "TOKEN_FILENAME", "TOKEN_DOCBLOCK", "TOKEN_VECTOR_SCALE", "TOKEN_GETTIME", "TOKEN_REALWAIT", "TOKEN_PROFILESTART", "TOKEN_PROFILESTOP", "TOKEN_FUNCTIONNAME_MACRO", "IF", "NEG",
  "$accept", "program", "using_list", "function_list", "class_object", "@1", "class_list", "$@2", "$@3", "optional_class_inheritance",
  "function_decl", "$@4", "function_object", "optional_funcflags", "optional_docblock", "formal_parameter_list", "formal_parameter", "optional_default_value", "statement_list", "statement",
  "nonempty_statement", "$@5", "$@6", "$@7", "optional_foreach", "post_op", "call_expression", "call", "basic_call", "optimized_calls",
  "nonempty_statement_2", "case_statement_list", "primitive_expression", "variable_expression", "function_call", "expression_list", "nonempty_expression_list", "expression", "optional_expression", "waittill_expression_list",
  "waittillmatch_expression_list", "filename"
};
}
