enum {
  TOKEN_YYerror = 0x100,
  TOKEN_YYUNDEF = 0x101,
  TOKEN_ERROR,
  TOKEN_TEXTBLOCK,
  TOKEN_STRING,
  TOKEN_IDENTIFIER,
  TOKEN_GREATER,
  TOKEN_LESS,
  TOKEN_SLASH,
  TOKEN_EQUALS,
  TOKEN_ESCAPECHAR
};
